version: "3"
services:

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: hello123
    volumes:
      - ./database_config:/docker-entrypoint-initdb.

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: